### ISSUE TITLE
error when mob bars text mode set true.

### ISSUE THREAD

**Issue by syrupderg** [DavideBlade/HealthBar-Reloaded#1]
[17:26:48 WARN]: java.lang.NullPointerException: at index 0
[17:26:48 WARN]: 	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:229)
[17:26:48 WARN]: 	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:219)
[17:26:48 WARN]: 	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:213)
[17:26:48 WARN]: 	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:353)
[17:26:48 WARN]: 	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:299)
[17:26:48 WARN]: 	at HealthBar-Reloaded.jar//com.gmail.davideblade99.healthbar.Settings.<init>(Settings.java:127)
[17:26:48 WARN]: 	at HealthBar-Reloaded.jar//com.gmail.davideblade99.healthbar.HealthBar.reloadConfigFromDisk(HealthBar.java:94)
[17:26:48 WARN]: 	at HealthBar-Reloaded.jar//com.gmail.davideblade99.healthbar.command.Commands.reloadConfigs(Commands.java:59)
[17:26:48 WARN]: 	at HealthBar-Reloaded.jar//com.gmail.davideblade99.healthbar.command.Commands.onCommand(Commands.java:44)
[17:26:48 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:26:48 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:26:48 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:981)
[17:26:48 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[17:26:48 WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[17:26:48 WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:321)
[17:26:48 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:305)
[17:26:48 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2379)
[17:26:48 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2339)
[17:26:48 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[17:26:48 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:26:48 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:26:48 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:26:48 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[17:26:48 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1345)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338)
[17:26:48 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1316)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204)
[17:26:48 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:26:48 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by DavideBlade** [comment]
Thank you for the report. I will check the problem in the next few days.
In the meantime could you send me your config.yml?
What version of Spigot are you using? (can you send me the output of the **/ver** command)

**Comment by syrupderg** [comment]
any setting works fine except when i set mob bars text mode true. im using purpur 1.19.3 version and i also use bungee/waterfall too.

**Comment by DavideBlade** [comment]
Can you copy and paste your config.yml? This will help me to better reproduce your problem

**Comment by DavideBlade** [comment]
The problem has been noticed and fixed in the new version 2.0.3 ([#ce007e5](https://github.com/DavideBlade/HealthBar-Reloaded/commit/607fe94fc73dbfec7c2f6767e4978d4bfdaad04c)). Thank you for the report! :)
