### ISSUE TITLE
plugin doesnt work in 1.21.1

### ISSUE THREAD

**Issue by TymekSL** [DavideBlade/HealthBar-Reloaded#20]
0:07:47 INFO]: [HealthBar-Reloaded] Enabling HealthBar-Reloaded v2.0.3.2
[00:07:47 INFO]: This version of HealthBar is compatible with the following versions: 1.17, 1.18, 1.19, 1.20
[00:07:47 INFO]: The server is on a different version and the plugin may not work properly
[00:07:47 ERROR]: Error occurred while enabling HealthBar-Reloaded v2.0.3.2 (Is it up to date?)
java.lang.NullPointerException: at index 0
        at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:232) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:222) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:216) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableList.construct(ImmutableList.java:353) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:299) ~[guava-32.1.2-jre.jar:?]
        at HealthBar-Reloaded.jar/com.gmail.davideblade99.healthbar.Settings.<init>(Settings.java:123) ~[HealthBar-Reloaded.jar:?]
        at HealthBar-Reloaded.jar/com.gmail.davideblade99.healthbar.HealthBar.onEnable(HealthBar.java:63) ~[HealthBar-Reloaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:07:47 INFO]: [HealthBar-Reloaded] Disabling HealthBar-Reloaded v2.0.3.2
[00:07:47 ERROR]: Error occurred while disabling HealthBar-Reloaded v2.0.3.2
java.lang.NullPointerException: Cannot invoke "com.gmail.davideblade99.healthbar.manager.PlayerBarManager.clearHealthBars()" because "this.playerBarManager" is null
        at HealthBar-Reloaded.jar/com.gmail.davideblade99.healthbar.HealthBar.onDisable(HealthBar.java:93) ~[HealthBar-Reloaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

paper spigot 1.21.1

**Comment by DavideBlade** [comment]
> [00:07:47 INFO]: This version of HealthBar is compatible with the following versions: 1.17, 1.18, 1.19, 1.20

As you can read, the version of the plugin you are using (2.0.3.2) supports up to 1.20.
For 1.21, you need to update the plugin.

**Comment by TymekSL** [comment]
ok but why you make this "INVALID" xd

**Comment by DavideBlade** [comment]
I don't have a more appropriate label. It is simply to say that there is no problem in the plugin :)
